### ISSUE TITLE
Typo in the Implementation

### ISSUE THREAD

**Issue by Akella17** [ikostrikov/pytorch-naf#16]
https://github.com/ikostrikov/pytorch-ddpg-naf/blob/d2e587a741e5220dfc6eceb7896ba7d6fe5c2630/naf.py#L121
current Target: r_t + \gamma * mask + v_{t+1}
correct Target: r_t + \gamma * mask * v_{t+1}

**Comment by ikostrikov** [comment]
Fixed in https://github.com/ikostrikov/pytorch-ddpg-naf/commit/d900aa6d7fc8f6eb263332a3334be28b49e83dc2
